// ============================================
// mock-data.ts - Marketplace Mock-Daten
// 
// Zweck: Realistische Testdaten für den Marketplace
// Verwendet von: Library Page, Detail Page
// ============================================

import type { MarketplaceModule, ModuleReview, ModuleDeveloper } from './types';
import { DEFAULT_LOCALE, type AppLocale } from '@/lib/i18n/config';
import { getCookieLocale, translateOwnedSystemText } from '@/lib/i18n/runtime';

// --------------------------------------------
// Entwickler-Profile
// Wiederverwendbare Developer-Daten
// --------------------------------------------

const developers: Record<string, ModuleDeveloper> = {
  lifeos: {
    id: 'lifeos-team',
    name: 'LifeOS Team',
    verified: true,
    website: 'https://lifeos.app',
  },
  productivity_labs: {
    id: 'productivity-labs',
    name: 'Productivity Labs',
    verified: true,
  },
  indie_dev: {
    id: 'indie-max',
    name: 'Max Müller',
    verified: false,
  },
  finance_tools: {
    id: 'finance-tools-gmbh',
    name: 'FinanceTools GmbH',
    verified: true,
    website: 'https://financetools.de',
  },
  health_apps: {
    id: 'health-apps',
    name: 'HealthApps Studio',
    verified: true,
  },
  edu_tech: {
    id: 'edu-tech',
    name: 'EduTech Solutions',
    verified: true,
  },
  game_studio: {
    id: 'pixel-games',
    name: 'Pixel Games Studio',
    verified: false,
  },
  ai_labs: {
    id: 'ai-labs',
    name: 'AI Labs Berlin',
    verified: true,
    website: 'https://ailabs.berlin',
  },
  dev_tools: {
    id: 'dev-tools-io',
    name: 'DevTools.io',
    verified: true,
  },
  creative_studio: {
    id: 'creative-studio',
    name: 'Creative Studio',
    verified: false,
  },
};

// --------------------------------------------
// APPS - Marketplace Module (type: 'apps')
// --------------------------------------------

const APP_MODULES: MarketplaceModule[] = [
  // Produktivität
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    slug: 'pomodoro-timer',
    type: 'apps',
    icon: 'Timer',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
    shortDescription: 'Fokussiertes Arbeiten mit der Pomodoro-Technik',
    fullDescription: `# Pomodoro Timer\n\nSteigere deine Produktivität mit der bewährten Pomodoro-Technik!\n\n## Features\n\n- **25-Minuten Arbeitsintervalle** mit 5-Minuten Pausen\n- **Anpassbare Timer** - Passe die Zeiten an deinen Workflow an\n- **Statistiken** - Verfolge deine tägliche und wöchentliche Produktivität`,
    category: 'productivity',
    tags: ['timer', 'focus', 'productivity', 'pomodoro'],
    pricing: { type: 'free' },
    developer: developers.productivity_labs,
    stats: { downloads: 45200, rating: 4.7, reviewCount: 892, weeklyGrowth: 12 },
    media: { screenshots: [] },
    technical: { version: '2.4.1', size: '156 KB', minLifeOSVersion: '1.0.0', permissions: ['notifications'], lastUpdated: '2026-01-15T10:00:00Z', releaseDate: '2025-03-20T10:00:00Z' },
    changelog: [{ version: '2.4.1', date: '2026-01-15T10:00:00Z', changes: ['Dark Mode Support', 'Verbesserte Statistiken'] }],
    isFeatured: true,
    isTrending: true,
    route: '/pomodoro-timer',
  },
  {
    id: 'habit-tracker-pro',
    name: 'Habit Tracker Pro',
    slug: 'habit-tracker-pro',
    type: 'apps',
    icon: 'Target',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
    shortDescription: 'Baue positive Gewohnheiten auf und tracke deinen Fortschritt',
    fullDescription: `# Habit Tracker Pro\n\nDein persönlicher Begleiter für bessere Gewohnheiten.\n\n## Features\n\n- **Unbegrenzte Habits**\n- **Streak-Tracking**\n- **Statistiken**`,
    category: 'productivity',
    tags: ['habits', 'tracking', 'goals', 'motivation'],
    pricing: { type: 'paid', price: 499, currency: 'EUR' },
    developer: developers.productivity_labs,
    stats: { downloads: 28400, rating: 4.8, reviewCount: 567, weeklyGrowth: 8 },
    media: { screenshots: [] },
    technical: { version: '3.1.0', size: '245 KB', minLifeOSVersion: '1.0.0', permissions: ['notifications', 'storage'], lastUpdated: '2026-01-20T10:00:00Z', releaseDate: '2025-01-15T10:00:00Z' },
    changelog: [{ version: '3.1.0', date: '2026-01-20T10:00:00Z', changes: ['Neue Kategorien', 'Performance-Optimierungen'] }],
    isFeatured: true,
    route: '/habit-tracker-pro',
  },
  {
    id: 'quick-notes',
    name: 'Quick Notes',
    slug: 'quick-notes',
    type: 'apps',
    icon: 'StickyNote',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    shortDescription: 'Schnelle Notizen mit Markdown-Support',
    fullDescription: `# Quick Notes\n\nGedanken festhalten, bevor sie verschwinden.`,
    category: 'productivity',
    tags: ['notes', 'markdown', 'writing'],
    pricing: { type: 'freemium', price: 299, currency: 'EUR' },
    developer: developers.indie_dev,
    stats: { downloads: 15600, rating: 4.3, reviewCount: 234, weeklyGrowth: 5 },
    media: { screenshots: [] },
    technical: { version: '1.8.2', size: '89 KB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-10T10:00:00Z', releaseDate: '2025-06-01T10:00:00Z' },
    changelog: [],
    route: '/quick-notes',
  },

  // Finanzen
  {
    id: 'budget-manager',
    name: 'Budget Manager',
    slug: 'budget-manager',
    type: 'apps',
    icon: 'PiggyBank',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    shortDescription: 'Behalte deine Finanzen im Griff mit smartem Budgeting',
    fullDescription: `# Budget Manager\n\nDein persönlicher Finanzberater.`,
    category: 'finance',
    tags: ['budget', 'money', 'finance', 'savings'],
    pricing: { type: 'freemium', price: 399, currency: 'EUR' },
    developer: developers.finance_tools,
    stats: { downloads: 38900, rating: 4.6, reviewCount: 723, weeklyGrowth: 15 },
    media: { screenshots: [] },
    technical: { version: '4.2.0', size: '312 KB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-25T10:00:00Z', releaseDate: '2024-09-01T10:00:00Z' },
    changelog: [],
    isTrending: true,
    route: '/budget-manager',
  },
  {
    id: 'investment-tracker',
    name: 'Investment Portfolio',
    slug: 'investment-tracker',
    type: 'apps',
    icon: 'TrendingUp',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    shortDescription: 'Verfolge deine Investments und Portfolio-Performance',
    fullDescription: `# Investment Portfolio\n\nBehalte den Überblick über deine Investments.`,
    category: 'finance',
    tags: ['investments', 'stocks', 'portfolio', 'crypto'],
    pricing: { type: 'subscription', price: 299, currency: 'EUR', interval: 'month' },
    developer: developers.finance_tools,
    stats: { downloads: 12300, rating: 4.5, reviewCount: 189, weeklyGrowth: 22 },
    media: { screenshots: [] },
    technical: { version: '1.5.0', size: '267 KB', minLifeOSVersion: '1.0.0', permissions: ['storage', 'network'], lastUpdated: '2026-01-28T10:00:00Z', releaseDate: '2025-08-01T10:00:00Z' },
    changelog: [],
    isNew: true,
    isTrending: true,
    route: '/investment-tracker',
  },

  // Gesundheit
  {
    id: 'meditation-timer',
    name: 'Meditation Timer',
    slug: 'meditation-timer',
    type: 'apps',
    icon: 'Flower2',
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #9333ea 100%)',
    shortDescription: 'Finde innere Ruhe mit geführten Meditationen',
    fullDescription: `# Meditation Timer\n\nDein Weg zu mehr Achtsamkeit.`,
    category: 'health',
    tags: ['meditation', 'mindfulness', 'relaxation', 'wellness'],
    pricing: { type: 'paid', price: 299, currency: 'EUR' },
    developer: developers.health_apps,
    stats: { downloads: 23400, rating: 4.9, reviewCount: 456, weeklyGrowth: 18 },
    media: { screenshots: [] },
    technical: { version: '3.0.0', size: '1.2 MB', minLifeOSVersion: '1.0.0', permissions: ['notifications', 'audio'], lastUpdated: '2026-01-22T10:00:00Z', releaseDate: '2025-04-01T10:00:00Z' },
    changelog: [],
    isFeatured: true,
    route: '/meditation-timer',
  },
  {
    id: 'workout-planner',
    name: 'Workout Planner',
    slug: 'workout-planner',
    type: 'apps',
    icon: 'Dumbbell',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    shortDescription: 'Plane und tracke deine Workouts',
    fullDescription: `# Workout Planner\n\nDein persönlicher Fitness-Coach.`,
    category: 'health',
    tags: ['fitness', 'workout', 'gym', 'exercise'],
    pricing: { type: 'freemium', price: 599, currency: 'EUR' },
    developer: developers.health_apps,
    stats: { downloads: 31200, rating: 4.6, reviewCount: 612, weeklyGrowth: 10 },
    media: { screenshots: [] },
    technical: { version: '2.8.0', size: '456 KB', minLifeOSVersion: '1.0.0', permissions: ['storage', 'notifications'], lastUpdated: '2026-01-18T10:00:00Z', releaseDate: '2025-05-15T10:00:00Z' },
    changelog: [],
    isTrending: true,
    route: '/workout-planner',
  },
  {
    id: 'sleep-tracker',
    name: 'Sleep Tracker',
    slug: 'sleep-tracker',
    type: 'apps',
    icon: 'Moon',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
    shortDescription: 'Verbessere deinen Schlaf mit intelligenter Analyse',
    fullDescription: `# Sleep Tracker\n\nBesserer Schlaf für ein besseres Leben.`,
    category: 'health',
    tags: ['sleep', 'health', 'tracking', 'wellness'],
    pricing: { type: 'free' },
    developer: developers.health_apps,
    stats: { downloads: 18700, rating: 4.2, reviewCount: 345, weeklyGrowth: 7 },
    media: { screenshots: [] },
    technical: { version: '1.4.0', size: '178 KB', minLifeOSVersion: '1.0.0', permissions: ['notifications'], lastUpdated: '2025-12-20T10:00:00Z', releaseDate: '2025-07-01T10:00:00Z' },
    changelog: [],
    route: '/sleep-tracker',
  },

  // Bildung
  {
    id: 'flashcards',
    name: 'Flashcards',
    slug: 'flashcards',
    type: 'apps',
    icon: 'Layers',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    shortDescription: 'Effektives Lernen mit Karteikarten und Spaced Repetition',
    fullDescription: `# Flashcards\n\nLerne effektiver mit wissenschaftlich bewährten Methoden.`,
    category: 'education',
    tags: ['learning', 'flashcards', 'study', 'education'],
    pricing: { type: 'free' },
    developer: developers.edu_tech,
    stats: { downloads: 42300, rating: 4.7, reviewCount: 834, weeklyGrowth: 6 },
    media: { screenshots: [] },
    technical: { version: '2.5.0', size: '198 KB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-12T10:00:00Z', releaseDate: '2025-01-01T10:00:00Z' },
    changelog: [],
    isFeatured: true,
    route: '/flashcards',
  },
  {
    id: 'language-learning',
    name: 'Language Lab',
    slug: 'language-learning',
    type: 'apps',
    icon: 'Languages',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
    shortDescription: 'Lerne neue Sprachen mit interaktiven Lektionen',
    fullDescription: `# Language Lab\n\nDein Weg zur Mehrsprachigkeit.`,
    category: 'education',
    tags: ['languages', 'learning', 'vocabulary'],
    pricing: { type: 'subscription', price: 999, currency: 'EUR', interval: 'month', trialDays: 7 },
    developer: developers.edu_tech,
    stats: { downloads: 27800, rating: 4.5, reviewCount: 521, weeklyGrowth: 14 },
    media: { screenshots: [] },
    technical: { version: '3.2.1', size: '2.1 MB', minLifeOSVersion: '1.0.0', permissions: ['audio', 'storage', 'network'], lastUpdated: '2026-01-26T10:00:00Z', releaseDate: '2025-03-01T10:00:00Z' },
    changelog: [],
    isTrending: true,
    route: '/language-learning',
  },

  // Spiele
  {
    id: 'sudoku',
    name: 'Sudoku',
    slug: 'sudoku',
    type: 'apps',
    icon: 'Grid3x3',
    color: '#2563eb',
    gradient: 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
    shortDescription: 'Täglich neue Sudoku-Rätsel in allen Schwierigkeiten',
    fullDescription: `# Sudoku\n\nDas beliebte Zahlenrätsel.`,
    category: 'games',
    tags: ['sudoku', 'puzzle', 'logic', 'brain'],
    pricing: { type: 'free' },
    developer: developers.game_studio,
    stats: { downloads: 28900, rating: 4.6, reviewCount: 534, weeklyGrowth: 3 },
    media: { screenshots: [] },
    technical: { version: '1.3.0', size: '87 KB', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2025-12-10T10:00:00Z', releaseDate: '2025-06-01T10:00:00Z' },
    changelog: [],
    route: '/sudoku',
  },
  {
    id: 'word-puzzle',
    name: 'Word Puzzle',
    slug: 'word-puzzle',
    type: 'apps',
    icon: 'Type',
    color: '#059669',
    gradient: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
    shortDescription: 'Wortspiele und Rätsel für Sprachliebhaber',
    fullDescription: `# Word Puzzle\n\nTrainiere deinen Wortschatz spielerisch.`,
    category: 'games',
    tags: ['words', 'puzzle', 'vocabulary', 'wordle'],
    pricing: { type: 'freemium', price: 199, currency: 'EUR' },
    developer: developers.game_studio,
    stats: { downloads: 15600, rating: 4.3, reviewCount: 267, weeklyGrowth: 8 },
    media: { screenshots: [] },
    technical: { version: '1.1.0', size: '134 KB', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2025-12-25T10:00:00Z', releaseDate: '2025-10-01T10:00:00Z' },
    changelog: [],
    isNew: true,
    route: '/word-puzzle',
  },

  // KI
  {
    id: 'ai-writing-assistant',
    name: 'AI Writing Assistant',
    slug: 'ai-writing-assistant',
    type: 'apps',
    icon: 'Sparkles',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    shortDescription: 'KI-gestützte Schreibhilfe für bessere Texte',
    fullDescription: `# AI Writing Assistant\n\nSchreibe schneller und besser mit KI-Unterstützung.`,
    category: 'ai',
    tags: ['ai', 'writing', 'text', 'assistant'],
    pricing: { type: 'subscription', price: 499, currency: 'EUR', interval: 'month' },
    developer: developers.ai_labs,
    stats: { downloads: 19200, rating: 4.7, reviewCount: 312, weeklyGrowth: 25 },
    media: { screenshots: [] },
    technical: { version: '1.8.0', size: '156 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-29T10:00:00Z', releaseDate: '2025-06-15T10:00:00Z' },
    changelog: [],
    isFeatured: true,
    isTrending: true,
    route: '/ai-writing-assistant',
  },

  // Developer
  {
    id: 'code-snippets',
    name: 'Code Snippets',
    slug: 'code-snippets',
    type: 'apps',
    icon: 'Code',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #64748b 0%, #475569 100%)',
    shortDescription: 'Speichere und organisiere deine Code-Snippets',
    fullDescription: `# Code Snippets\n\nDeine persönliche Code-Bibliothek.`,
    category: 'developer',
    tags: ['code', 'snippets', 'programming', 'developer'],
    pricing: { type: 'free' },
    developer: developers.dev_tools,
    stats: { downloads: 21300, rating: 4.5, reviewCount: 389, weeklyGrowth: 4 },
    media: { screenshots: [] },
    technical: { version: '2.2.0', size: '234 KB', minLifeOSVersion: '1.0.0', permissions: ['storage', 'network'], lastUpdated: '2026-01-08T10:00:00Z', releaseDate: '2025-02-15T10:00:00Z' },
    changelog: [],
    route: '/code-snippets',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    slug: 'api-tester',
    type: 'apps',
    icon: 'Send',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    shortDescription: 'Teste REST APIs direkt in LifeOS',
    fullDescription: `# API Tester\n\nPostman-Alternative direkt in LifeOS.`,
    category: 'developer',
    tags: ['api', 'rest', 'http', 'developer', 'testing'],
    pricing: { type: 'free' },
    developer: developers.dev_tools,
    stats: { downloads: 14200, rating: 4.4, reviewCount: 234, weeklyGrowth: 6 },
    media: { screenshots: [] },
    technical: { version: '1.5.0', size: '178 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2025-12-18T10:00:00Z', releaseDate: '2025-05-01T10:00:00Z' },
    changelog: [],
    route: '/api-tester',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    type: 'apps',
    icon: 'FileJson',
    color: '#eab308',
    gradient: 'linear-gradient(135deg, #eab308 0%, #ca8a04 100%)',
    shortDescription: 'Formatiere, validiere und transformiere JSON',
    fullDescription: `# JSON Formatter\n\nDas Schweizer Taschenmesser für JSON.`,
    category: 'developer',
    tags: ['json', 'formatter', 'developer', 'tools'],
    pricing: { type: 'free' },
    developer: developers.dev_tools,
    stats: { downloads: 32100, rating: 4.6, reviewCount: 567, weeklyGrowth: 2 },
    media: { screenshots: [] },
    technical: { version: '1.8.0', size: '67 KB', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2025-11-20T10:00:00Z', releaseDate: '2025-01-10T10:00:00Z' },
    changelog: [],
    route: '/json-formatter',
  },

  // Lifestyle
  {
    id: 'mood-journal',
    name: 'Mood Journal',
    slug: 'mood-journal',
    type: 'apps',
    icon: 'Heart',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
    shortDescription: 'Tracke deine Stimmung und entdecke Muster',
    fullDescription: `# Mood Journal\n\nVerstehe deine Emotionen besser.`,
    category: 'lifestyle',
    tags: ['mood', 'journal', 'emotions', 'mental health'],
    pricing: { type: 'free' },
    developer: developers.health_apps,
    stats: { downloads: 16800, rating: 4.5, reviewCount: 289, weeklyGrowth: 9 },
    media: { screenshots: [] },
    technical: { version: '2.1.0', size: '145 KB', minLifeOSVersion: '1.0.0', permissions: ['notifications', 'storage'], lastUpdated: '2026-01-14T10:00:00Z', releaseDate: '2025-04-01T10:00:00Z' },
    changelog: [],
    route: '/mood-journal',
  },
  {
    id: 'recipe-manager',
    name: 'Recipe Manager',
    slug: 'recipe-manager',
    type: 'apps',
    icon: 'ChefHat',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    shortDescription: 'Sammle und organisiere deine Lieblingsrezepte',
    fullDescription: `# Recipe Manager\n\nDein digitales Kochbuch.`,
    category: 'lifestyle',
    tags: ['recipes', 'cooking', 'food', 'meal planning'],
    pricing: { type: 'freemium', price: 299, currency: 'EUR' },
    developer: developers.creative_studio,
    stats: { downloads: 8900, rating: 4.3, reviewCount: 145, weeklyGrowth: 11 },
    media: { screenshots: [] },
    technical: { version: '1.4.0', size: '234 KB', minLifeOSVersion: '1.0.0', permissions: ['storage', 'network'], lastUpdated: '2026-01-19T10:00:00Z', releaseDate: '2025-08-15T10:00:00Z' },
    changelog: [],
    isNew: true,
    route: '/recipe-manager',
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    slug: 'color-palette',
    type: 'apps',
    icon: 'Palette',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    shortDescription: 'Erstelle und speichere Farbpaletten für deine Projekte',
    fullDescription: `# Color Palette\n\nDas Tool für Designer und Kreative.`,
    category: 'creative',
    tags: ['colors', 'design', 'palette', 'creative'],
    pricing: { type: 'free' },
    developer: developers.creative_studio,
    stats: { downloads: 11200, rating: 4.4, reviewCount: 178, weeklyGrowth: 5 },
    media: { screenshots: [] },
    technical: { version: '1.2.0', size: '98 KB', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2025-12-05T10:00:00Z', releaseDate: '2025-07-15T10:00:00Z' },
    changelog: [],
    route: '/color-palette',
  },
  {
    id: 'base-personal-hub',
    name: 'Base: Personal Hub',
    slug: 'base-personal-hub',
    type: 'apps',
    entityType: 'base',
    baseCategory: 'personal',
    icon: 'FolderTree',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    shortDescription: 'Persönliche Organisation mit Kalender, Inbox und Gewohnheiten.',
    fullDescription: `# Personal Hub\n\nEine Base-Vorlage für dein persönliches LifeOS-System.\n\n## Zweck\n\n- Tagesplanung und Routinen\n- persönliche Kommunikation\n- private Organisation\n\n## Geeignet für\n\n- Einzelpersonen\n- persönliche Produktivität\n- Alltag und Selbstmanagement`,
    category: 'lifestyle',
    tags: ['base', 'personal', 'template', 'organization', 'starter'],
    includedModules: ['calendar', 'inbox', 'habit-tracker-pro', 'mood-journal'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 9200, rating: 4.8, reviewCount: 241, weeklyGrowth: 17 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: 'N/A', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2026-02-10T10:00:00Z', releaseDate: '2026-02-01T10:00:00Z' },
    changelog: [],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'base-business-ops',
    name: 'Base: Business Ops',
    slug: 'base-business-ops',
    type: 'apps',
    entityType: 'base',
    baseCategory: 'business',
    icon: 'Building2',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0e7490 100%)',
    shortDescription: 'Vorlage für Teamprozesse, Finanzen und operative Steuerung.',
    fullDescription: `# Business Ops\n\nEine Base-Vorlage für operative Geschäftsprozesse und Teamsteuerung.\n\n## Zweck\n\n- Unternehmenssteuerung\n- Finanzübersicht\n- Team-Dokumentation\n\n## Geeignet für\n\n- kleine Teams\n- Gründer:innen\n- tägliche operative Arbeit`,
    category: 'productivity',
    tags: ['base', 'business', 'operations', 'template', 'team'],
    includedModules: ['budget-manager', 'investment-tracker', 'quick-notes', 'browser'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 6100, rating: 4.7, reviewCount: 123, weeklyGrowth: 14 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: 'N/A', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2026-02-10T10:00:00Z', releaseDate: '2026-02-01T10:00:00Z' },
    changelog: [],
    isNew: true,
  },
  {
    id: 'base-education-lab',
    name: 'Base: Education Lab',
    slug: 'base-education-lab',
    type: 'apps',
    entityType: 'base',
    baseCategory: 'education',
    icon: 'GraduationCap',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
    shortDescription: 'Lern-Base mit Lernkarten, Sprache und Notizen.',
    fullDescription: `# Education Lab\n\nEine Base-Vorlage für Lernen und Wissensaufbau.\n\n## Zweck\n\n- Lernplanung\n- Wissensmanagement\n- Kursorganisation\n\n## Geeignet für\n\n- Schüler:innen\n- Studierende\n- Selbstlerner`,
    category: 'education',
    tags: ['base', 'education', 'learning', 'template', 'starter'],
    includedModules: ['flashcards', 'language-learning', 'quick-notes', 'browser'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 5300, rating: 4.9, reviewCount: 97, weeklyGrowth: 21 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: 'N/A', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2026-02-10T10:00:00Z', releaseDate: '2026-02-01T10:00:00Z' },
    changelog: [],
    isNew: true,
  },
  {
    id: 'base-creator-studio',
    name: 'Base: Creator Studio',
    slug: 'base-creator-studio',
    type: 'apps',
    entityType: 'base',
    baseCategory: 'creative',
    icon: 'Palette',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    shortDescription: 'Setup für kreative Workflows, Ideenfindung und Content-Produktion.',
    fullDescription: `# Creator Studio\n\nEine Base-Vorlage für kreative Produktion und Ideenmanagement.\n\n## Zweck\n\n- Ideen sammeln und clustern\n- Assets und Farbwelten organisieren\n- Content-Workflows strukturieren\n\n## Geeignet für\n\n- Creator\n- Designer:innen\n- Content Teams`,
    category: 'creative',
    tags: ['base', 'creative', 'studio', 'template', 'team'],
    includedModules: ['color-palette', 'quick-notes', 'browser', 'mood-journal'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 4700, rating: 4.6, reviewCount: 84, weeklyGrowth: 19 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: 'N/A', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2026-02-10T10:00:00Z', releaseDate: '2026-02-02T10:00:00Z' },
    changelog: [],
    isNew: true,
  },
  {
    id: 'base-health-routine',
    name: 'Base: Health Routine',
    slug: 'base-health-routine',
    type: 'apps',
    entityType: 'base',
    baseCategory: 'health',
    icon: 'Heart',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)',
    shortDescription: 'Struktur für Bewegung, Schlaf, Achtsamkeit und persönliche Routinen.',
    fullDescription: `# Health Routine\n\nEine Base-Vorlage für gesunde Gewohnheiten und Wohlbefinden.\n\n## Zweck\n\n- Routinen für Fitness und Schlaf\n- mentale Balance und Fokus\n- tägliche Gesundheits-Checks\n\n## Geeignet für\n\n- Fitness-Einsteiger:innen\n- Routine-orientierte Nutzer:innen\n- Gesundheits-Tracking`,
    category: 'health',
    tags: ['base', 'health', 'wellness', 'template', 'personal'],
    includedModules: ['workout-planner', 'sleep-tracker', 'meditation-timer', 'habit-tracker-pro'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 5600, rating: 4.8, reviewCount: 102, weeklyGrowth: 16 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: 'N/A', minLifeOSVersion: '1.0.0', permissions: [], lastUpdated: '2026-02-10T10:00:00Z', releaseDate: '2026-02-03T10:00:00Z' },
    changelog: [],
    isNew: true,
    isTrending: true,
  },
];

// --------------------------------------------
// MODELS - AI Modelle (type: 'models')
// --------------------------------------------

const MODEL_MODULES: MarketplaceModule[] = [
  {
    id: 'model-textgen-pro',
    name: 'TextGen Pro 7B',
    slug: 'model-textgen-pro',
    type: 'models',
    icon: 'MessageSquare',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    shortDescription: 'Schnelles Sprachmodell für Textgenerierung und Chat',
    fullDescription: `# TextGen Pro 7B\n\nEin schnelles und effizientes Sprachmodell für Textgenerierung.\n\n## Anwendungen\n\n- Chat und Konversation\n- Textzusammenfassung\n- Kreatives Schreiben`,
    category: 'ai',
    tags: ['text-generation', 'llm', 'chat', 'nlp'],
    pricing: { type: 'free' },
    developer: developers.ai_labs,
    stats: { downloads: 156000, rating: 4.6, reviewCount: 2341, weeklyGrowth: 8 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: '4.2 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-20T10:00:00Z', releaseDate: '2025-09-01T10:00:00Z' },
    changelog: [],
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'model-anyflow-core',
    name: 'AnyFlow Core',
    slug: 'model-anyflow-core',
    type: 'models',
    icon: 'Sparkles',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    shortDescription: 'Multimodales Modell für Text, Bild und Audio',
    fullDescription: `# AnyFlow Core\n\nMultimodales KI-Modell für vielseitige Anwendungen.`,
    category: 'ai',
    tags: ['any-to-any', 'multimodal', 'vision', 'audio'],
    pricing: { type: 'subscription', price: 1999, currency: 'EUR', interval: 'month' },
    developer: developers.ai_labs,
    stats: { downloads: 89000, rating: 4.8, reviewCount: 1567, weeklyGrowth: 15 },
    media: { screenshots: [] },
    technical: { version: '2.1.0', size: '8.5 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage', 'audio'], lastUpdated: '2026-01-25T10:00:00Z', releaseDate: '2025-06-15T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'model-visionchat',
    name: 'VisionChat 3B',
    slug: 'model-visionchat',
    type: 'models',
    icon: 'Eye',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    shortDescription: 'Bild + Text → Text für visuelle QA und Captioning',
    fullDescription: `# VisionChat 3B\n\nVisuelles Sprachmodell für Bildverständnis.`,
    category: 'ai',
    tags: ['image-text-to-text', 'vision', 'captioning', 'ocr'],
    pricing: { type: 'free' },
    developer: developers.ai_labs,
    stats: { downloads: 67000, rating: 4.4, reviewCount: 987, weeklyGrowth: 12 },
    media: { screenshots: [] },
    technical: { version: '1.2.0', size: '2.8 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-18T10:00:00Z', releaseDate: '2025-07-20T10:00:00Z' },
    changelog: [],
    isTrending: true,
  },
  {
    id: 'model-ocr-nova',
    name: 'OCR Nova',
    slug: 'model-ocr-nova',
    type: 'models',
    icon: 'FileText',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    shortDescription: 'Image‑to‑Text für Dokumente und Scans',
    fullDescription: `# OCR Nova\n\nPräzise Texterkennung aus Bildern und Dokumenten.`,
    category: 'ai',
    tags: ['image-to-text', 'ocr', 'document', 'extraction'],
    pricing: { type: 'freemium', price: 499, currency: 'EUR' },
    developer: developers.ai_labs,
    stats: { downloads: 45000, rating: 4.7, reviewCount: 756, weeklyGrowth: 6 },
    media: { screenshots: [] },
    technical: { version: '3.0.0', size: '1.5 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-22T10:00:00Z', releaseDate: '2025-04-10T10:00:00Z' },
    changelog: [],
  },
  {
    id: 'model-refinex',
    name: 'RefineX',
    slug: 'model-refinex',
    type: 'models',
    icon: 'ImagePlus',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
    shortDescription: 'Image‑to‑Image für Stiltransfer und Upscaling',
    fullDescription: `# RefineX\n\nBildverbesserung und Stiltransfer.`,
    category: 'ai',
    tags: ['image-to-image', 'upscaling', 'style-transfer', 'enhancement'],
    pricing: { type: 'paid', price: 999, currency: 'EUR' },
    developer: developers.ai_labs,
    stats: { downloads: 34000, rating: 4.5, reviewCount: 534, weeklyGrowth: 9 },
    media: { screenshots: [] },
    technical: { version: '2.0.0', size: '3.2 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-15T10:00:00Z', releaseDate: '2025-08-05T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'model-renderflow',
    name: 'RenderFlow',
    slug: 'model-renderflow',
    type: 'models',
    icon: 'Image',
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #7c3aed 100%)',
    shortDescription: 'Text‑to‑Image für schnelle Visualisierung',
    fullDescription: `# RenderFlow\n\nErstelle Bilder aus Textbeschreibungen.`,
    category: 'ai',
    tags: ['text-to-image', 'generation', 'diffusion', 'art'],
    pricing: { type: 'subscription', price: 799, currency: 'EUR', interval: 'month' },
    developer: developers.ai_labs,
    stats: { downloads: 78000, rating: 4.6, reviewCount: 1234, weeklyGrowth: 18 },
    media: { screenshots: [] },
    technical: { version: '1.5.0', size: '5.8 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-28T10:00:00Z', releaseDate: '2025-05-20T10:00:00Z' },
    changelog: [],
    isTrending: true,
  },
  {
    id: 'model-motionpilot',
    name: 'MotionPilot',
    slug: 'model-motionpilot',
    type: 'models',
    icon: 'Video',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
    shortDescription: 'Text‑to‑Video für kurze Clips und Promos',
    fullDescription: `# MotionPilot\n\nGeneriere Videos aus Textbeschreibungen.`,
    category: 'ai',
    tags: ['text-to-video', 'generation', 'animation', 'clips'],
    pricing: { type: 'subscription', price: 2499, currency: 'EUR', interval: 'month' },
    developer: developers.ai_labs,
    stats: { downloads: 23000, rating: 4.3, reviewCount: 345, weeklyGrowth: 28 },
    media: { screenshots: [] },
    technical: { version: '0.9.0', size: '12.4 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage'], lastUpdated: '2026-01-26T10:00:00Z', releaseDate: '2025-11-01T10:00:00Z' },
    changelog: [],
    isNew: true,
  },
  {
    id: 'model-voiceforge',
    name: 'VoiceForge',
    slug: 'model-voiceforge',
    type: 'models',
    icon: 'Mic',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    shortDescription: 'Text‑to‑Speech für natürliche Stimmen',
    fullDescription: `# VoiceForge\n\nNatürliche Sprachsynthese in 20+ Sprachen.`,
    category: 'ai',
    tags: ['text-to-speech', 'tts', 'voice', 'audio'],
    pricing: { type: 'freemium', price: 399, currency: 'EUR' },
    developer: developers.ai_labs,
    stats: { downloads: 56000, rating: 4.7, reviewCount: 876, weeklyGrowth: 11 },
    media: { screenshots: [] },
    technical: { version: '2.3.0', size: '1.8 GB', minLifeOSVersion: '1.0.0', permissions: ['network', 'storage', 'audio'], lastUpdated: '2026-01-24T10:00:00Z', releaseDate: '2025-03-15T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
];

// --------------------------------------------
// INTEGRATIONS - Externe Dienste (type: 'integrations')
// --------------------------------------------

const INTEGRATION_MODULES: MarketplaceModule[] = [
  {
    id: 'integration-slack',
    name: 'Slack Integration',
    slug: 'integration-slack',
    type: 'integrations',
    icon: 'MessageSquare',
    color: '#7c3aed',
    gradient: 'linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)',
    shortDescription: 'Benachrichtigungen und Workflows in Slack Channels',
    fullDescription: `# Slack Integration\n\nVerbinde LifeOS mit deinem Slack Workspace.`,
    category: 'integrations',
    tags: ['slack', 'messaging', 'notifications', 'team'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 89000, rating: 4.6, reviewCount: 1234, weeklyGrowth: 5 },
    media: { screenshots: [] },
    technical: { version: '2.0.0', size: '45 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-20T10:00:00Z', releaseDate: '2025-02-01T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'integration-google-calendar',
    name: 'Google Calendar',
    slug: 'integration-google-calendar',
    type: 'integrations',
    icon: 'Calendar',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    shortDescription: 'Termine lesen/schreiben inkl. Erinnerungen',
    fullDescription: `# Google Calendar\n\nSynchronisiere deine Google Kalender mit LifeOS.`,
    category: 'integrations',
    tags: ['google', 'calendar', 'sync', 'events'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 156000, rating: 4.8, reviewCount: 2567, weeklyGrowth: 8 },
    media: { screenshots: [] },
    technical: { version: '3.1.0', size: '67 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-25T10:00:00Z', releaseDate: '2025-01-15T10:00:00Z' },
    changelog: [],
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'integration-stripe',
    name: 'Stripe Payments',
    slug: 'integration-stripe',
    type: 'integrations',
    icon: 'CreditCard',
    color: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
    shortDescription: 'Zahlungen, Kunden und Abos verwalten',
    fullDescription: `# Stripe Payments\n\nIntegriere Stripe für Zahlungsabwicklung.`,
    category: 'integrations',
    tags: ['stripe', 'payments', 'billing', 'subscriptions'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 45000, rating: 4.5, reviewCount: 678, weeklyGrowth: 12 },
    media: { screenshots: [] },
    technical: { version: '1.8.0', size: '56 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-18T10:00:00Z', releaseDate: '2025-04-01T10:00:00Z' },
    changelog: [],
  },
  {
    id: 'integration-notion',
    name: 'Notion Sync',
    slug: 'integration-notion',
    type: 'integrations',
    icon: 'FileText',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #64748b 0%, #475569 100%)',
    shortDescription: 'Datenbanken lesen/schreiben für Wissensräume',
    fullDescription: `# Notion Sync\n\nSynchronisiere Notion Datenbanken mit LifeOS.`,
    category: 'integrations',
    tags: ['notion', 'sync', 'database', 'knowledge'],
    pricing: { type: 'freemium', price: 299, currency: 'EUR' },
    developer: developers.lifeos,
    stats: { downloads: 78000, rating: 4.4, reviewCount: 1123, weeklyGrowth: 7 },
    media: { screenshots: [] },
    technical: { version: '2.2.0', size: '78 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-22T10:00:00Z', releaseDate: '2025-03-15T10:00:00Z' },
    changelog: [],
    isTrending: true,
  },
  {
    id: 'integration-github',
    name: 'GitHub Integration',
    slug: 'integration-github',
    type: 'integrations',
    icon: 'Github',
    color: '#1f2937',
    gradient: 'linear-gradient(135deg, #374151 0%, #1f2937 100%)',
    shortDescription: 'Issues, PRs und Repos direkt in LifeOS verwalten',
    fullDescription: `# GitHub Integration\n\nDeine GitHub Projekte in LifeOS.`,
    category: 'integrations',
    tags: ['github', 'git', 'code', 'development'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 67000, rating: 4.7, reviewCount: 945, weeklyGrowth: 9 },
    media: { screenshots: [] },
    technical: { version: '2.5.0', size: '89 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-28T10:00:00Z', releaseDate: '2025-02-20T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'integration-zapier',
    name: 'Zapier Connect',
    slug: 'integration-zapier',
    type: 'integrations',
    icon: 'Zap',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    shortDescription: 'Automatisierungen mit 5000+ Apps verbinden',
    fullDescription: `# Zapier Connect\n\nVerbinde LifeOS mit tausenden von Apps.`,
    category: 'integrations',
    tags: ['zapier', 'automation', 'workflow', 'apps'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 34000, rating: 4.3, reviewCount: 456, weeklyGrowth: 15 },
    media: { screenshots: [] },
    technical: { version: '1.2.0', size: '34 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-15T10:00:00Z', releaseDate: '2025-06-01T10:00:00Z' },
    changelog: [],
    isNew: true,
  },
  {
    id: 'integration-todoist',
    name: 'Todoist Sync',
    slug: 'integration-todoist',
    type: 'integrations',
    icon: 'CheckSquare',
    color: '#dc2626',
    gradient: 'linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)',
    shortDescription: 'Aufgaben zwischen LifeOS und Todoist synchronisieren',
    fullDescription: `# Todoist Sync\n\nDeine Todoist Aufgaben in LifeOS.`,
    category: 'integrations',
    tags: ['todoist', 'tasks', 'sync', 'productivity'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 56000, rating: 4.6, reviewCount: 789, weeklyGrowth: 6 },
    media: { screenshots: [] },
    technical: { version: '1.5.0', size: '45 KB', minLifeOSVersion: '1.0.0', permissions: ['network'], lastUpdated: '2026-01-12T10:00:00Z', releaseDate: '2025-05-15T10:00:00Z' },
    changelog: [],
  },
  {
    id: 'integration-spotify',
    name: 'Spotify Player',
    slug: 'integration-spotify',
    type: 'integrations',
    icon: 'Music',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
    shortDescription: 'Musik steuern und Playlists in LifeOS verwalten',
    fullDescription: `# Spotify Player\n\nDeine Musik direkt in LifeOS.`,
    category: 'integrations',
    tags: ['spotify', 'music', 'player', 'streaming'],
    pricing: { type: 'free' },
    developer: developers.lifeos,
    stats: { downloads: 89000, rating: 4.5, reviewCount: 1345, weeklyGrowth: 4 },
    media: { screenshots: [] },
    technical: { version: '2.0.0', size: '67 KB', minLifeOSVersion: '1.0.0', permissions: ['network', 'audio'], lastUpdated: '2026-01-20T10:00:00Z', releaseDate: '2025-04-10T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
];

// --------------------------------------------
// DATASETS - Datensätze für Training (type: 'datasets')
// --------------------------------------------

const DATASET_MODULES: MarketplaceModule[] = [
  {
    id: 'dataset-support-tickets',
    name: 'Support Tickets (DE)',
    slug: 'dataset-support-tickets',
    type: 'datasets',
    icon: 'MessageCircle',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    shortDescription: 'Klassifikation und Routing für Support-Anfragen',
    fullDescription: `# Support Tickets (DE)\n\n50.000 annotierte Support-Tickets auf Deutsch.`,
    category: 'ai',
    tags: ['support', 'classification', 'german', 'customer-service'],
    pricing: { type: 'free' },
    developer: developers.ai_labs,
    stats: { downloads: 12000, rating: 4.5, reviewCount: 234, weeklyGrowth: 8 },
    media: { screenshots: [] },
    technical: { version: '2.0.0', size: '156 MB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-15T10:00:00Z', releaseDate: '2025-06-01T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'dataset-product-reviews',
    name: 'Produkt‑Reviews',
    slug: 'dataset-product-reviews',
    type: 'datasets',
    icon: 'Star',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    shortDescription: 'Sentiment und Themenextraktion aus Reviews',
    fullDescription: `# Produkt-Reviews\n\n100.000 E-Commerce Reviews mit Sentiment Labels.`,
    category: 'ai',
    tags: ['sentiment', 'reviews', 'ecommerce', 'analysis'],
    pricing: { type: 'free' },
    developer: developers.ai_labs,
    stats: { downloads: 8900, rating: 4.3, reviewCount: 156, weeklyGrowth: 5 },
    media: { screenshots: [] },
    technical: { version: '1.5.0', size: '234 MB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-10T10:00:00Z', releaseDate: '2025-07-15T10:00:00Z' },
    changelog: [],
  },
  {
    id: 'dataset-meeting-notes',
    name: 'Meeting Notes',
    slug: 'dataset-meeting-notes',
    type: 'datasets',
    icon: 'FileText',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
    shortDescription: 'Zusammenfassungen und Aktionspunkte',
    fullDescription: `# Meeting Notes\n\n25.000 Meeting-Transkripte mit Zusammenfassungen.`,
    category: 'ai',
    tags: ['meetings', 'summarization', 'action-items', 'transcription'],
    pricing: { type: 'paid', price: 2999, currency: 'EUR' },
    developer: developers.ai_labs,
    stats: { downloads: 5600, rating: 4.6, reviewCount: 89, weeklyGrowth: 12 },
    media: { screenshots: [] },
    technical: { version: '1.0.0', size: '456 MB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-20T10:00:00Z', releaseDate: '2025-09-01T10:00:00Z' },
    changelog: [],
    isTrending: true,
  },
  {
    id: 'dataset-code-comments',
    name: 'Code Comments',
    slug: 'dataset-code-comments',
    type: 'datasets',
    icon: 'Code',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #64748b 0%, #475569 100%)',
    shortDescription: 'Code-Snippets mit Dokumentations-Kommentaren',
    fullDescription: `# Code Comments\n\n500.000 Code-Snippets mit generierten Kommentaren.`,
    category: 'ai',
    tags: ['code', 'documentation', 'comments', 'programming'],
    pricing: { type: 'free' },
    developer: developers.dev_tools,
    stats: { downloads: 15000, rating: 4.4, reviewCount: 267, weeklyGrowth: 7 },
    media: { screenshots: [] },
    technical: { version: '1.2.0', size: '1.2 GB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-18T10:00:00Z', releaseDate: '2025-05-20T10:00:00Z' },
    changelog: [],
    isFeatured: true,
  },
  {
    id: 'dataset-email-classification',
    name: 'Email Classification',
    slug: 'dataset-email-classification',
    type: 'datasets',
    icon: 'Mail',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    shortDescription: 'E-Mail Kategorisierung und Priorität',
    fullDescription: `# Email Classification\n\n200.000 E-Mails mit Kategorie-Labels.`,
    category: 'ai',
    tags: ['email', 'classification', 'priority', 'inbox'],
    pricing: { type: 'freemium', price: 999, currency: 'EUR' },
    developer: developers.ai_labs,
    stats: { downloads: 7800, rating: 4.2, reviewCount: 134, weeklyGrowth: 9 },
    media: { screenshots: [] },
    technical: { version: '1.1.0', size: '345 MB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-12T10:00:00Z', releaseDate: '2025-08-10T10:00:00Z' },
    changelog: [],
  },
  {
    id: 'dataset-conversation-pairs',
    name: 'Conversation Pairs',
    slug: 'dataset-conversation-pairs',
    type: 'datasets',
    icon: 'MessageSquare',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
    shortDescription: 'Dialog-Paare für Chatbot-Training',
    fullDescription: `# Conversation Pairs\n\n1 Million Dialog-Paare für Chatbot-Finetuning.`,
    category: 'ai',
    tags: ['conversation', 'chatbot', 'dialog', 'training'],
    pricing: { type: 'subscription', price: 499, currency: 'EUR', interval: 'month' },
    developer: developers.ai_labs,
    stats: { downloads: 23000, rating: 4.7, reviewCount: 456, weeklyGrowth: 15 },
    media: { screenshots: [] },
    technical: { version: '3.0.0', size: '2.3 GB', minLifeOSVersion: '1.0.0', permissions: ['storage'], lastUpdated: '2026-01-25T10:00:00Z', releaseDate: '2025-04-01T10:00:00Z' },
    changelog: [],
    isTrending: true,
    isFeatured: true,
  },
];

// --------------------------------------------
// Alle Module zusammenführen
// --------------------------------------------

export const MARKETPLACE_MODULES: MarketplaceModule[] = [
  ...APP_MODULES,
  ...MODEL_MODULES,
  ...INTEGRATION_MODULES,
  ...DATASET_MODULES,
];

function getRuntimeLocale(): AppLocale {
  return typeof document === 'undefined' ? DEFAULT_LOCALE : getCookieLocale();
}

function localizeMarketplaceModule(
  module: MarketplaceModule,
  locale: AppLocale
): MarketplaceModule {
  return {
    ...module,
    name: translateOwnedSystemText(module.name, locale),
    shortDescription: translateOwnedSystemText(module.shortDescription, locale),
    fullDescription: translateOwnedSystemText(module.fullDescription, locale),
    developer: {
      ...module.developer,
      name: translateOwnedSystemText(module.developer.name, locale),
    },
    changelog: module.changelog.map((entry) => ({
      ...entry,
      changes: entry.changes.map((change) => translateOwnedSystemText(change, locale)),
    })),
  };
}

function localizeReview(review: ModuleReview, locale: AppLocale): ModuleReview {
  return {
    ...review,
    title: translateOwnedSystemText(review.title, locale),
    content: translateOwnedSystemText(review.content, locale),
    developerResponse: review.developerResponse
      ? {
          ...review.developerResponse,
          content: translateOwnedSystemText(review.developerResponse.content, locale),
        }
      : undefined,
  };
}

// --------------------------------------------
// Mock Reviews
// --------------------------------------------

export const MOCK_REVIEWS: ModuleReview[] = [
  {
    id: 'review-1',
    moduleId: 'pomodoro-timer',
    userId: 'user-1',
    userName: 'Sarah K.',
    rating: 5,
    title: 'Perfekt für fokussiertes Arbeiten!',
    content: 'Nutze den Timer jetzt seit 3 Monaten täglich. Sehr empfehlenswert!',
    createdAt: '2026-01-10T14:30:00Z',
    helpfulCount: 42,
    developerResponse: {
      content: 'Vielen Dank für das tolle Feedback!',
      createdAt: '2026-01-11T09:00:00Z',
    },
  },
  {
    id: 'review-2',
    moduleId: 'pomodoro-timer',
    userId: 'user-2',
    userName: 'Michael B.',
    rating: 4,
    title: 'Gut, aber könnte mehr Features haben',
    content: 'Solider Timer, macht was er soll.',
    createdAt: '2026-01-05T10:15:00Z',
    helpfulCount: 18,
  },
  {
    id: 'review-3',
    moduleId: 'habit-tracker-pro',
    userId: 'user-4',
    userName: 'Thomas H.',
    rating: 5,
    title: 'Bester Habit Tracker!',
    content: 'Die Streaks motivieren wirklich!',
    createdAt: '2026-01-15T08:30:00Z',
    helpfulCount: 31,
  },
];

// --------------------------------------------
// Hilfsfunktionen
// --------------------------------------------

export function getModuleById(id: string): MarketplaceModule | undefined {
  const locale = getRuntimeLocale();
  const moduleEntry = MARKETPLACE_MODULES.find(m => m.id === id);
  return moduleEntry ? localizeMarketplaceModule(moduleEntry, locale) : undefined;
}

export function getModuleBySlug(slug: string): MarketplaceModule | undefined {
  const locale = getRuntimeLocale();
  const moduleEntry = MARKETPLACE_MODULES.find(m => m.slug === slug);
  return moduleEntry ? localizeMarketplaceModule(moduleEntry, locale) : undefined;
}

export function getReviewsForModule(moduleId: string): ModuleReview[] {
  const locale = getRuntimeLocale();
  return MOCK_REVIEWS.filter(r => r.moduleId === moduleId).map((review) =>
    localizeReview(review, locale)
  );
}

export function getFeaturedModules(type?: string): MarketplaceModule[] {
  const locale = getRuntimeLocale();
  return MARKETPLACE_MODULES
    .filter(m => m.isFeatured && (!type || m.type === type))
    .map((module) => localizeMarketplaceModule(module, locale));
}

export function getTrendingModules(type?: string): MarketplaceModule[] {
  const locale = getRuntimeLocale();
  return MARKETPLACE_MODULES
    .filter(m => m.isTrending && (!type || m.type === type))
    .map((module) => localizeMarketplaceModule(module, locale));
}

export function getNewModules(type?: string): MarketplaceModule[] {
  const locale = getRuntimeLocale();
  return MARKETPLACE_MODULES
    .filter(m => m.isNew && (!type || m.type === type))
    .map((module) => localizeMarketplaceModule(module, locale));
}

export function getModulesByType(type: string): MarketplaceModule[] {
  const locale = getRuntimeLocale();
  return MARKETPLACE_MODULES
    .filter(m => m.type === type)
    .map((module) => localizeMarketplaceModule(module, locale));
}

export function getModulesByCategory(category: string): MarketplaceModule[] {
  const locale = getRuntimeLocale();
  const modules = category === 'all'
    ? MARKETPLACE_MODULES
    : MARKETPLACE_MODULES.filter(m => m.category === category);
  return modules.map((module) => localizeMarketplaceModule(module, locale));
}

export function getRatingDistribution(moduleId: string): Record<number, number> {
  const reviews = getReviewsForModule(moduleId);
  const distribution: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  reviews.forEach(r => { distribution[r.rating]++; });
  return distribution;
}
